combined JUnit test reports that are uploaded via dorny/test-reporter

diff --git a/.github/workflows/dev_java21.yml b/.github/workflows/dev_java21.yml
--- a/.github/workflows/dev_java21.yml
+++ b/.github/workflows/dev_java21.yml
@@ -37,7 +37,7 @@ jobs:
           cache: ${{ env.SETUP_JAVA_CACHE }}
 
       - name: Run Unit Tests via Maven
-        run: mvn --batch-mode --no-transfer-progress clean test
+        run: mvn --batch-mode --no-transfer-progress dependency:list clean test
 
       - name: Upload JUnit Test Report as Artifact
         uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
@@ -49,32 +49,35 @@ jobs:
             service/target/surefire-reports/*.xml
             service-api/target/surefire-reports/*.xml
 
-      - name: Publish JUnit Test Report - Core
+      - name: Publish JUnit Test Reports
         uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
         if: success() || failure()
         with:
-          name: JUnit Test Report - Core
-          path: core/target/surefire-reports/*.xml
+          name: JUnit Test Reports
+          path: |
+            core/target/surefire-reports/*.xml,
+            service/target/surefire-reports/*.xml,
+            service-api/target/surefire-reports/*.xml
           reporter: java-junit
           fail-on-error: true
 
-      - name: Publish JUnit Test Report - Service
-        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
-        if: success() || failure()
-        with:
-          name: JUnit Test Report - Service
-          path: service/target/surefire-reports/*.xml
-          reporter: java-junit
-          fail-on-error: true
-
-      - name: Publish JUnit Test Report - Service-API
-        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
-        if: success() || failure()
-        with:
-          name: JUnit Test Report - Service-API
-          path: service-api/target/surefire-reports/*.xml
-          reporter: java-junit
-          fail-on-error: true
+#      - name: Publish JUnit Test Report - Service
+#        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
+#        if: success() || failure()
+#        with:
+#          name: JUnit Test Report - Service
+#          path: service/target/surefire-reports/*.xml
+#          reporter: java-junit
+#          fail-on-error: true
+#
+#      - name: Publish JUnit Test Report - Service-API
+#        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
+#        if: success() || failure()
+#        with:
+#          name: JUnit Test Report - Service-API
+#          path: service-api/target/surefire-reports/*.xml
+#          reporter: java-junit
+#          fail-on-error: true
 
   build:
     name: Build Backend
@@ -92,4 +95,4 @@ jobs:
           cache: ${{ env.SETUP_JAVA_CACHE }}
 
       - name: Build a JAR package via Maven
-        run: mvn --batch-mode --no-transfer-progress -DskipTests clean package
+        run: mvn --batch-mode --no-transfer-progress -DskipTests dependency:list clean package
